# -*- coding: utf-8 -*-
"""HW_Data_Manipulation_Alif Gala Buana.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YtovfqZ7c4-CIBAY_i_EmEmruqgJn2Lj
"""

# --- Data Manipulation ----
import pandas as pd
pd.set_option("display.max_columns",None) #menampilkan semua coloumn biar gak titiktitik

#--- Numerical Computation ----
import numpy as np

df = pd.read_csv("telco_customer_churn.csv")

df.head()

df.info()

df

"""## Soal 1
Buat fungsi Python untuk memfilter churn untuk menemukan pelanggan yang berisiko tinggi.
Pelanggan berisiko tinggi didefinisikan sebagai pelanggan yang memiliki kontrak bulanan
dan tagihan bulanan yang tinggi (di atas persentil 90%).

"""

## data pelanggan dengan kontrak bulanan
pelanggan_highrisk = df[df["Contract"] == "Month-to-month"]
pelanggan_highrisk

p_90 = np.percentile(df['MonthlyCharges'], 90)
p_90

#memfilter pelanggan dengan kontrak bulanan dan tagihan bulanan tinggi (percentile 90%)
pelanggan_highrisk = df[(df["Contract"] == "Month-to-month") & (df["MonthlyCharges"] >= p_90)]
pelanggan_highrisk

"""## Soal 2
Buat script Python untuk mengelompokkan data berdasarkan jenis kontrak dan menghitung
rata-rata tagihan bulanan serta persentase churn untuk setiap grup (1 dan 0, rata rata untuk
menghitung persentase)
"""

group_1 = df.groupby(["Contract","Churn"]).agg({"MonthlyCharges" : "mean"})
group_1

group_2 = ((df.groupby(["Contract"])["Churn"].value_counts(normalize=True))*100).round(2).astype(str) + '%'
group_2

group_final = pd.merge(group_1, group_2, on =['Contract', 'Churn'] , how='left')
group_final.rename(columns = {"proportion" : "percentage Churn"}, inplace=True)
group_final

"""## Soal 3:
Buat pivot table untuk menganalisis hubungan antara jenis kontrak dan metode pembayaran
terhadap rata-rata tagihan bulanan.
"""

tabel_pivot = pd.pivot_table(df, values='MonthlyCharges', index='Contract', columns='PaymentMethod', aggfunc='count')
tabel_pivot

"""## Soal 4
Buat crosstab untuk mengevaluasi hubungan antara churn dan metode pembayaran, serta
menghitung persentase churn untuk setiap metode pembayaran.
"""

# crostab hubungan antara paymentmethod dengan churn
crosstab = pd.crosstab(df['PaymentMethod'], df['Churn'])
crosstab

# crosstab persentase churn pada setiap metode pembayaran dalam persen
crosstab_persen = pd.crosstab(df['PaymentMethod'], df['Churn'], margins= True,normalize = 'index')
crosstab_persen

"""# Soal 5
Buat aggregation untuk mengevaluasi total churn dengan senior citizen yes dan dependents
lebih dari 0, serta menghitung total churn dari gender dengan kontrak year.

"""

df['Churn'] = df['Churn'].map({'Yes': 1, 'No': 0})

df.info()

x = df[(df["SeniorCitizen"] > 0) & (df["Dependents"] == "Yes") & (df["Churn"] >0)]
x

#mengevaluasi total churn terhadap seniorcitizen yes dan dependants yes
agg = x.groupby(["SeniorCitizen","Dependents"]).agg({"Churn" : "sum"})
agg



#menghitung total churn terhadap gender dengan kontrak year
y = df[(df["Contract"] != "Month-to-month") & (df["Churn"] >0)]
y

#mengevaluasi total churn terhadap seniorcitizen yes dan dependants yes
agg2 = y.groupby(["gender","Contract"]).agg({"Churn" : "sum"})
agg2