# -*- coding: utf-8 -*-
"""AS_DS27_Day6_Alif Gala Buana.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wSHw3u0D1Rjrsjn0Sx2QMDkEywyClmD_

## AS_DS27_Day6_Alif Gala Buana


---

## Poin Assignment :
**1.** Plot barplot pada city, masih kurang informatif. Pertanyaan :
1. Bagaimana caranya supaya Barplot memiliki tampilan informatif ?
2. Tulis insightnya ya !

`clue` nomer 1 : coba pahami tentang `value_counts`, ambil 10 atau 5 nilai teratas saja. kemudian buat barplot dan tulis insightnya (60 poin)

**2.** Lakukan eksplorasi dan mencoba looping pada kolom dan baris dataframe `dataset_day6.csv`
- for loop (15 poin)
- while loop (15 poin)
- nested loop (10 poin)

`clue` nomer 2 :
- pahamilah definisi dataframe pada `slide 4 PPT Data Type and Structure Part 2`
- anggap dataframe memiliki `index` yang bisa kita looping serta `kolom` yang bisa kita akses sebagai `dictionary` maupun `list` atau `array`
- pahami tentang `iterrows` pada dokumentasi ini : https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iterrows.html
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('dataset_day6.csv')
df

df['City'].value_counts()

# Barplot untuk Gender (Nominal)
sns.countplot(x='City', data=df)
plt.title('Barplot of City')
plt.xlabel('City')
plt.ylabel('Count')
plt.show()

"""## Plot barplot diatas, masih kurang informatif. Ini jadi Assignment supaya bisa informatif :)

## Soal Nomor 1
"""

# Barplot untuk Gender (Nominal) slicing data (10)
sns.countplot(x='City', data=df, order = df['City'].value_counts().index[:10], hue= 'City', palette= sns.color_palette())
plt.title('Barplot of City')
plt.xlabel('City')
plt.ylabel('Count')
plt.show()

"""## insight
#### data yang ditampilkan merupakan 10 urutan row nama kota/city yang memiliki data terbanyak di dataframe, dari dataframe tersebut terlihat pada orang-orang yang terdata tersebut paling banyak berasal dari Banda Aceh yaitu sebanyak 546 orang dan paling sedikit berasal dari makasar yaitu 505 orang, akan tetapi dapat kita lihat penyebaran lokasi kota dari dataframe  relatif merata dan tidak berselisih jauh diantara 10 kota tersebut.

# SOAL NOMOR 2

##  While loop
"""

i = 0
while i <len (df['Age']): #fungsi while loop dengan parameter len.
    i+=1
    if i <100:
        print (df['Age'].iloc[i], df['Marital Status'].iloc [i])

"""## For loop"""

for index, row in df.iloc[:100].iterrows(): #fungsi for loop untuk dataframe dengan indeks 0-100
    if row['Age'] <= 50:
        print(row['Age'], row['Marital Status'])

"""## Nested Loop"""

for x_index, x_row in df.iloc[0:100].iterrows(): #looping pertama
    L1 = x_row['Salary']
    L2 = x_row['Marital Status']
    for y_index, y_row in df.iloc[x_index+1:100].iterrows(): # Loooping kedua
        L3 = y_row['Salary']
        L4 = y_row['Marital Status']
        print (L3,L4)